//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int MarkID { get; set; }
        public string Name { get; set; }
        public string Theme { get; set; }
        public string Country { get; set; }
        public string Feature { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int Edition { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> CollectionID { get; set; }
    
        public virtual Collection Collection { get; set; }
    }
}
